### ISSUE TITLE
Unable to detect TransportService.h

### ISSUE THREAD

**Issue by shiveshkhaitan** [fkie/iop_core#1]
In file included from 
/iop_ws/src/iop/iop_core/iop_events_fkie/src/EventsPlugin.h:28:0,
                 from /iop_ws/src/iop/iop_core/iop_events_fkie/src/EventsPlugin.cpp:23:
/iop_ws/build_isolated/iop_events_fkie/jaus/Iop_events_fkie_0/include/urn_jaus_jss_core_Events/EventsService.h:14:58: fatal error: urn_jaus_jss_core_Transport/TransportService.h: No such file or directory
In file included from /iop_ws/src/iop/iop_core/iop_events_fkie/src/EventsClientPlugin.h:29:0,
                 from /iop_ws/src/iop/iop_core/iop_events_fkie/src/EventsClientPlugin.cpp:23:
/iop_ws/build_isolated/iop_events_fkie/jaus/Iop_events_fkie_0/include/urn_jaus_jss_core_EventsClient/EventsClientService.h:14:58: fatal error: urn_jaus_jss_core_Transport/TransportService.h: No such file or directory

This is the error I get during catkin_make. What can be the problem?

**Comment by atiderko** [comment]
while build process some generated header file are copied to the include folder in devel space.
Did you sourced the setup.sh from your devel space?
I did not build the packages using catkin_make. You can try to build it with `catkin build`.

**Comment by shiveshkhaitan** [comment]
Thank you..  Catkin build worked

**Comment by shiveshkhaitan** [comment]
The catkin build for jaustoolset is stuck since 2 hours. I have tried to build multiple times but it always stops at jaustoolset. It is supposed to take time?

**Comment by atiderko** [comment]
no it should take only few minutes first time, because it downloads sources from https://github.com/fkie-forks/jaustoolset
My college has same issue today. Please delete  folder ```catkin_ws/src/iop/jaustoolset``` and ```catkin_ws/build/jaustoolset```. Then try to build again...

**Comment by shiveshkhaitan** [comment]
Thank you. It worked
